name: Docker Image Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f Dockerfiles/test.Dockerfile -t yuanokazaki/okazaki-yuan-intro-to-devops-a2:test-latest .
